-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 14:18:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Good`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Good` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supply` (
  `id` INT NOT NULL,
  `Good_id` INT NOT NULL,
  `Supplier_id` INT NOT NULL,
  `stock` INT NULL,
  `price` DECIMAL(10,2) NULL,
  `shippingtime` INT NULL,
  INDEX `fk_Supply_Good_idx` (`Good_id` ASC) VISIBLE,
  INDEX `fk_Supply_Supplier1_idx` (`Supplier_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Supply_Good`
    FOREIGN KEY (`Good_id`)
    REFERENCES `mydb`.`Good` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Supply_Supplier1`
    FOREIGN KEY (`Supplier_id`)
    REFERENCES `mydb`.`Supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sale` (
  `id` INT NOT NULL,
  `percent` DECIMAL(4,2) NULL,
  `type` ENUM('QUANTITY', 'BILLTOTAL', 'TIME') NULL,
  `value` VARCHAR(45) NULL,
  `Supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Sale_Supplier1_idx` (`Supplier_id` ASC) VISIBLE,
  CONSTRAINT `fk_Sale_Supplier1`
    FOREIGN KEY (`Supplier_id`)
    REFERENCES `mydb`.`Supplier` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
